## Importo librerías y cargo el dataset "nbaplayersdraft.csv"

In [1]:
import pandas as pd
import numpy as np

# cargo el dataset
jugadores = pd.read_csv('../datos/raw/nbaplayersdraft.csv')

In [2]:
jugadores.info()

<class 'pandas.DataFrame'>
RangeIndex: 1922 entries, 0 to 1921
Data columns (total 24 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   id                         1922 non-null   int64
 1   year                       1922 non-null   int64
 2   rank                       1922 non-null   int64
 3   overall_pick               1922 non-null   int64
 4   team                       1922 non-null   str
 5   player                     1922 non-null   str
 6   college                    1585 non-null   str
 7   years_active               1669 non-null   float64
 8   games                      1669 non-null   float64
 9   minutes_played             1669 non-null   float64
 10  points                     1669 non-null   float64
 11  total_rebounds             1669 non-null   float64
 12  assists                    1669 non-null   float64
 13  field_goal_percentage      1665 non-null   float64
 14  3_point_percentage         1545 non-null   float64
 15  free_throw_percentage      1633 non-null   float64
 16  average_minutes_played     1669 non-null   float64
 17  points_per_game            1669 non-null   float64
 18  average_total_rebounds     1669 non-null   float64
 19  average_assists            1669 non-null   float64
 20  win_shares                 1669 non-null   float64
 21  win_shares_per_48_minutes  1668 non-null   float64
 22  box_plus_minus             1668 non-null   float64
 23  value_over_replacement     1669 non-null   float64
dtypes: float64(17), int64(4), str(3)
memory usage: 405.1 KB

In [4]:
jugadores.describe()

,id,year,rank,overall_pick,years_active,games,minutes_played,points,total_rebounds,assists,...,3_point_percentage,free_throw_percentage,average_minutes_played,points_per_game,average_total_rebounds,average_assists,win_shares,win_shares_per_48_minutes,box_plus_minus,value_over_replacement
count,1922.000000,1922.000000,1922.000000,1922.000000,1669.000000,1669.000000,1669.000000,1669.000000,1669.000000,1669.000000,...,1545.000000,1633.000000,1669.000000,1669.000000,1669.000000,1669.000000,1669.000000,1668.000000,1668.000000,1669.000000
mean,961.500000,2005.317378,29.694589,29.694589,6.332534,348.042540,8399.055722,3580.413421,1497.009587,774.300779,...,0.272405,0.716825,18.134032,7.275734,3.194368,1.550749,17.873697,0.061691,-2.311271,4.403176
std,554.977927,9.456946,16.912454,16.912454,4.656321,324.897567,9845.871529,4826.142847,2003.686388,1284.602969,...,0.128339,0.118702,8.707656,4.969343,2.083895,1.488536,27.989805,0.094467,4.143403,11.461729
min,1.000000,1989.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-1.700000,-1.264000,-52.000000,-8.500000
25%,481.250000,1997.000000,15.000000,15.000000,2.000000,72.000000,838.000000,265.000000,128.000000,46.000000,...,0.222000,0.659000,11.000000,3.400000,1.700000,0.500000,0.400000,0.030000,-3.900000,-0.400000
50%,961.500000,2005.000000,30.000000,30.000000,5.000000,235.000000,4204.000000,1552.000000,656.000000,257.000000,...,0.317000,0.736000,17.700000,6.200000,2.800000,1.100000,5.300000,0.069000,-2.000000,0.000000
75%,1441.750000,2013.000000,44.000000,44.000000,10.000000,584.000000,13246.000000,5150.000000,2139.000000,910.000000,...,0.356000,0.797000,24.800000,10.000000,4.200000,2.100000,24.500000,0.104000,-0.300000,4.500000
max,1922.000000,2021.000000,60.000000,60.000000,22.000000,1541.000000,52139.000000,37062.000000,15091.000000,12091.000000,...,1.000000,1.000000,41.100000,27.200000,13.300000,9.500000,249.500000,1.442000,51.100000,142.600000

In [5]:
jugadores.head()

,id,year,rank,overall_pick,team,player,college,years_active,games,minutes_played,...,3_point_percentage,free_throw_percentage,average_minutes_played,points_per_game,average_total_rebounds,average_assists,win_shares,win_shares_per_48_minutes,box_plus_minus,value_over_replacement
0,1,1989,1,1,SAC,Pervis Ellison,Louisville,11.0,474.0,11593.0,...,0.050,0.689,24.5,9.5,6.7,1.5,21.8,0.090,-0.5,4.4
1,2,1989,2,2,LAC,Danny Ferry,Duke,13.0,917.0,18133.0,...,0.393,0.840,19.8,7.0,2.8,1.3,34.8,0.092,-0.9,4.9
2,3,1989,3,3,SAS,Sean Elliott,Arizona,12.0,742.0,24502.0,...,0.375,0.799,33.0,14.2,4.3,2.6,55.7,0.109,0.2,13.5
3,4,1989,4,4,MIA,Glen Rice,Michigan,15.0,1000.0,34985.0,...,0.400,0.846,35.0,18.3,4.4,2.1,88.7,0.122,0.8,24.9
4,5,1989,5,5,CHH,J.R. Reid,UNC,11.0,672.0,15370.0,...,0.135,0.716,22.9,8.5,5.0,1.0,22.5,0.070,-2.9,-3.7

Miro cuántos registros son únicos.

In [6]:
print(jugadores['player'].nunique())

1916

Tengo 1916 registros únicos de 1922. Algunos jugadores están repetidos. Miro a ver cuáles son y por qué.

In [8]:
# filtro para ver los jugadores que comparten nombre
nombres_duplicados = jugadores[jugadores.duplicated(subset=['player'], keep=False)]

# ordeno por nombre para compararlos cara a cara
print(nombres_duplicados[['year', 'overall_pick', 'team', 'player', 'college']].sort_values('player'))

      year  overall_pick team           player                  college
547   1998            51  MIA     Corey Brewer                 Oklahoma
1028  2007             7  MIN     Corey Brewer                  Florida
72    1990            19  BOS        Dee Brown  Jacksonville University
1007  2006            46  UTA        Dee Brown                 Illinois
1636  2017            15  POR   Justin Jackson                      UNC
1724  2018            43  DEN   Justin Jackson                 Maryland
1184  2009            43  MIA  Marcus Thornton                      LSU
1546  2015            45  BOS  Marcus Thornton           William & Mary
983   2006            22  NJN  Marcus Williams                    UConn
1054  2007            33  SAS  Marcus Williams                  Arizona
12    1989            13  BOS    Michael Smith                      BYU
304   1994            35  SAC    Michael Smith               Providence

La realidad es que no estaban duplicados, sino que son jugadores distintos que comparten nombre y apellido. Por lo tanto, no tengo que eliminar esos registros. Sí tengo que sustituir los nulos en la columna "college" por su valor. En realidad esos valores no son nulos, sino que corresponden a jugadores que no pasaron por la universidad (la mayoría llegaron desde Europa). Convierto los NaN en "No universitario".

In [ ]:
# reemplazo los valores nulos por una etiqueta
jugadores['college'] = jugadores['college'].fillna('No universitario')
# cuento las universidades más comunes
jugadores['college'].value_counts()

college
No universitario         337
Kentucky                  58
Duke                      57
Arizona                   43
UNC                       43
                        ...
Missouri State             1
UT Arlington               1
Belmont                    1
Yale                       1
John A. Logan College      1
Name: count, Length: 238, dtype: int64

Ahora comienza la verdadera limpieza de variables. Creo una lista con las columnas que necesitan de esa limpieza, transformo valores extraños en NaN y relleno todos los NaN con un 0.0 (es como si un jugador hubiese estado 0 minutos en la NBA, con 0 puntos y 0 rebotes).

In [11]:
# Creamos la lista con todas las columnas numéricas de rendimiento
columnas_estadisticas = [
    'years_active', 'games', 'minutes_played', 'points', 'total_rebounds', 'assists',
    'field_goal_percentage', '3_point_percentage', 'free_throw_percentage',
    'average_minutes_played', 'points_per_game', 'average_total_rebounds', 'average_assists',
    'win_shares', 'win_shares_per_48_minutes', 'box_plus_minus', 'value_over_replacement'
]

# Forzamos la conversión a tipo numérico y rellenamos con 0.0 sobre tu DataFrame
for col in columnas_estadisticas:
    jugadores[col] = pd.to_numeric(jugadores[col], errors='coerce')
    jugadores[col] = jugadores[col].fillna(0.0)

Como la columna "id" es redundante, también la elimino.

In [13]:
jugadores = jugadores.drop(columns=['id'])

Busco si quedan valores nulos en el dataframe y cuáles son sus dimensiones finales.

In [15]:
print(f"Valores nulos totales: {jugadores.isnull().sum().sum()}")
print(f"Dimensiones finales del dataframe: {jugadores.shape}")

Valores nulos totales: 0
Dimensiones finales del dataframe: (1922, 23)

Perfecto, ya tengo el dataframe listo para ser utilizado con modelos. Me han quedado 1922 registros y 23 columnas. Sin ningún valor nulo. Ahora lo que me queda es guardarlo en la carpeta de procesados del repositorio.

In [17]:
jugadores.to_csv('../datos/procesados/nbaplayersdraft_limpio.csv', index=False)